### ISSUE TITLE
intership -> practice 

### ISSUE THREAD

**Issue by VanyaXIII** [daniil-vikulov/daniil-vikulov#1]
Здравствуйте, Даниил! Я был с Вами в одной команде во время упомянутых мероприятий от jetbrains. С моей точки зрения, да и в общем понимании, ```intership``` это другое. Пожалуйста, замените это слово на более корректное, например, ```practice```

**Comment by danvik13** [comment]
Hey, VanyaXIII!

Thank you for your attention to the details. I fully embrace your point of view and appreciate a possible solution you have provided.

Nevertheless, after careful consideration, I came to the conclusion that the use of the term "intership" in this context reflects the specifics of our project and meets generally accepted standards in our field. This term helps to accurately convey the level of engagement and the nature of the work that the participants performed.

Best wishes,
Daniel
