### ISSUE TITLE
Proposal: add Greg Biryukov as a mentor or coach

### ISSUE THREAD

**Issue by VanyaXIII** [daniil-vikulov/daniil-vikulov#2]
Здравствуйте, Даниил! Наверное, Вы не будете спорить со мной, что влияние Бирюкова Григория Алексеевича на Ваши проекты и на Ваш путь в мире IT в целом нельзя переоценить. В частности, вся идейная и математическая часть таких проектов, как AstraTor и unreal fluid зиждется, на идеях и формулах, которые Грегорий перенес из KartohaEngine в свою легендарную Billiard Game, откуда уже и попали к Вам. Также со стороны Григория была огромная менторская поддержка остальных проектов. 

Мне кажется, что это стоит упомянуть и это будет только в плюс к Вашей биографии

**Comment by danvik13** [comment]
ГРЫГОР
